VPNServer: main.o tun_interface.o userdb.o
	g++ -o VPNServer main.o tun_interface.o userdb.o
main.o: main.cpp common.h tun_interface.h userdb.h
	g++ -c main.cpp -I.
userdb.o: userdb.cpp userdb.h
	g++ -c userdb.cpp -I.
tun_interface.o: tun_interface.cpp tun_interface.h
	g++ -c tun_interface.cpp -I.
clean:
	rm -f *.o VPNServer